# Generated by Django 2.2.1 on 2019-10-02 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Текст'), ('button', 'Кнопка')], default='text', max_length=50, verbose_name='тип')),
                ('text', models.TextField(verbose_name='текст')),
                ('next', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.Message', verbose_name='следующий')),
            ],
            options={
                'verbose_name': 'сообщеение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст')),
                ('type', models.CharField(choices=[('text', 'Текст'), ('button', 'Кнопка')], default='text', max_length=50, verbose_name='тип')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.Answer', verbose_name='предшественник')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
    ]
